import { useRef, useState } from "react";
import PromptInput from "./components/PromptInput.jsx";
import LoadingState from "./components/LoadingState.jsx";
import ErrorState from "./components/ErrorState.jsx";
import ResultView from "./components/ResultView.jsx";
import { generateStudyMaterial } from "./lib/api.js";
import { validateResult } from "./lib/validateResult.js";

// status: "idle" | "loading" | "error" | "success"
export default function App() {
  const [status, setStatus] = useState("idle");
  const [data, setData] = useState(null);
  const [errorReason, setErrorReason] = useState(null);
  const [lastInput, setLastInput] = useState("");

  // Guards against a slow earlier request resolving after a newer one and
  // silently overwriting the correct result with stale data.
  const requestId = useRef(0);

  async function handleGenerate(input) {
    const id = ++requestId.current;
    setLastInput(input);
    setStatus("loading");
    setErrorReason(null);

    try {
      const raw = await generateStudyMaterial(input);
      if (id !== requestId.current) return; // a newer request has since started

      const result = validateResult(raw);
      if (!result.ok) {
        setErrorReason(result.reason);
        setStatus("error");
        return;
      }

      setData(result.data);
      setStatus("success");
    } catch (err) {
      if (id !== requestId.current) return;
      setErrorReason(err.code === "failed_to_fetch" ? "network" : err.code || "request_failed");
      setStatus("error");
    }
  }

  function handleRetry() {
    if (lastInput) handleGenerate(lastInput);
  }

  function handleReset() {
    requestId.current++; // invalidate any in-flight request
    setStatus("idle");
    setData(null);
    setErrorReason(null);
    setLastInput("");
  }

  return (
    <div className="app">
      <header className="app-header">
        <h1>📚 Study Assistant</h1>
        <p>Paste your notes or a topic — get flashcards and a quiz, generated by AI.</p>
      </header>

      <main className="app-main">
        {status !== "success" && (
          <PromptInput onSubmit={handleGenerate} disabled={status === "loading"} />
        )}

        {status === "loading" && <LoadingState />}
        {status === "error" && <ErrorState reason={errorReason} onRetry={handleRetry} />}
        {status === "success" && data && <ResultView data={data} onReset={handleReset} />}
      </main>

      <footer className="app-footer">
        <p>Built for the Flam frontend internship assignment.</p>
      </footer>
    </div>
  );
}
